service: ClinicalImgV1
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  memorySize: 512
functions:
  app:
    handler: server/app.handler
    events:
    - http:
          path: /
          method: get
          cors: true
      - http:
          path: /getSummary
          method: post
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
